### 商品一覧取得
GET http://localhost:8080/api/products

### 商品詳細取得
GET http://localhost:8080/api/products/1

### カートに追加
POST http://localhost:8080/api/cart
content-type: application/json

{
    "productId": 1, 
    "quantity": 2
}

### カート取得
GET http://localhost:8080/api/cart


### 注文
POST http://localhost:8080/api/orders
content-type: application/json


{"customerInfo":{
        "customerName": "テスト",
        "customerAddress": "購入者住所",
        "customerEmail": "t@e.com",
        "shippingName": "配送先氏名",
        "shippingAddress": "住所",
        "payMethod": "cod"},
  "items": [
    {
        "productId": 7,
        "quantity": 6
    }
  ]
}
###管理者ログイン（正常系）
POST http://localhost:8080/admin/auth/login
Content-Type: application/x-www-form-urlencoded

email=admin@example.com&password=adminpass

###管理者ログアウト（正常系）
POST http://localhost:8080/admin/auth/logout
Cookie: {{login.response.headers.Set-Cookie}}

### ログイン失敗（登録されていないメールアドレス）
POST http://localhost:8080/admin/auth/login
Content-Type: application/x-www-form-urlencoded

email=unknown@test.com&password=adminpass

### ログイン失敗（パスワード不一致）
POST http://localhost:8080/admin/auth/login
Content-Type: application/x-www-form-urlencoded

email=admin@example.com&password=wrongpasswor



### ステータス更新時にDBエラーが発生する（異常系）
PATCH http://localhost:8080/admin/order/9999
Content-Type: application/json

{
  "newStatus": "SHIPPED"
}