### 商品一覧取得
GET http://localhost:8080/api/products

### 商品詳細取得
GET http://localhost:8080/api/products/1

### カートに追加
POST http://localhost:8080/api/cart
content-type: application/json

{
    "productId": 1, 
    "quantity": 2
}

### カート取得
GET http://localhost:8080/api/cart


### 注文
POST http://localhost:8080/api/orders
content-type: application/json


{"customerInfo":{
        "customerName": "テスト",
        "customerAddress": "購入者住所",
        "customerEmail": "t@e.com",
        "shippingName": "配送先氏名",
        "shippingAddress": "住所",
        "payMethod": "代引き"},
  "items": [
    {
        "productId": 7,
        "quantity": 6
    }
  ]
}